//
//  SnapShotTaskType.swift
//  SnapShot
//
//  Created by 张磊 on 16/1/14.
//  Copyright © 2016年 Jacob Li. All rights reserved.
//

import Foundation

// TaskType
let TASK_TYPE_LOGIN: Int = 1
let TASK_TYPE_REGISTER: Int = 2
let TASK_TYPE_GET_VERIFY_CODE: Int = 3
let TASK_TYPE_GET_HOME_PAGES: Int = 4
let TASK_TYPE_GET_USER_INFO: Int = 5
let TASK_TYPE_MODIFY_USER_NAME: Int = 6
let TASK_TYPE_MODIFY_PASSWORD: Int = 7
let TASK_TYPE_ENROLL_GROUP_SHOT: Int = 8
let TASK_TYPE_GET_RECOMMENDED_SPECIAL_SHOT: Int = 9
let TASK_TYPE_GET_SPECIAL_SHOT_DETAIL: Int = 10
let TASK_TYPE_GET_RECOMMENDED_PHOTOGRAPHER: Int = 11
let TASK_TYPE_GET_PHOTOGRAPHER_BASE_DETAIL: Int = 12
let TASK_TYPE_GET_PHOTOGRAPHER_PRODUCT: Int = 13